### ISSUE TITLE
Warning occurs on each add to watch window

### ISSUE THREAD

**Issue by smitgd** [monnerat/insight#10]
Each time a typical variable is added to the watch window a warning pops up saying:

"Expression is not an assignment (and might have no effect)"

It doesn't stop the item from being watched but it is still annoying (and unexpected).  The warning is coming from binutils-gdb/gdb/printcmd.c in function set_command(). It is intended to warn the user in command line GDB that an attempt to set a variable had no effect, such as "set loops==100" or even "set loops". 

The attached patch file suppresses the warning when 1) a variable is set with no value assigned, 2) when a machine register is set with no value assigned and 3) when a "convenience" variable is set with no value assigned. Apparently insight's hooks into GDB when adding watch items cause values to be "set" with no value assigned.

[008-Avoid-warning-on-every-add-to-watch.patch.zip](https://github.com/monnerat/insight/files/455716/008-Avoid-warning-on-every-add-to-watch.patch.zip)

Adding this patch file to patches/binutils-gdb and re-running "configure..." + "make all install" fixes the problem in insight.

**Comment by smitgd** [comment]
Went ahead and made a pull request to add the patch...

**Comment by smitgd** [comment]
Modified the 008-... patch file as seen in updated pull request #11.

**Comment by monnerat** [comment]
Hi smitgd,
Thanks a lot for the problem report.
When possible, I really prefer to fix in the gdbtk code that I have control on, rather than using gdb submodule patches (used only when they cannot be avoided), thus I've fixed the problem my way (https://github.com/monnerat/insight/commit/3da2ed25c75238cf2f11a0d2f528c2306834375b).
Many thanks for the patch anyway.
Regards,
Patrick

**Comment by smitgd** [comment]
No idea how that fixes it but it does. Thanks!
Got rid of my patch and pulled in your fix and re-built. Works great.
(Did see one error on build but pulling in updates on binutils-gdb fixed it.)
