### ISSUE TITLE
Running insight on Ubuntu 16.04 64-bit

### ISSUE THREAD

**Issue by frederiklikaj** [monnerat/insight#13]
hello,

Regarding insight (i am learning assembly by Jeff Duntemann's book "Assembly language step by step")
i have followed everything as in her:
https://github.com/monnerat/insight
The insight directory is now in my /root folder.

root@LIKAJF:~# pwd
/root
root@LIKAJF:~# ls
insight
root@LIKAJF:~# cd insight/
root@LIKAJF:~/insight# ls
autom4te.cache  config.log     configure.ac  libgui    README
binutils-gdb    config.status  COPYING       Makefile  testsuite
bundle          configure      gdbtk         patches
root@LIKAJF:~/insight# 

But how do i run insight from terminal to debug .asm files.
I get "no insight command found" when itry to run it.

Thank you in advance for your help.

**Comment by monnerat** [comment]
After compilation, you have to install it somewhere.

For Ubuntu, I recommend you to follow the directives at http://www.dalfonso.co/2016/04/23/setting-insight-debugger-on-ubuntu-16-04-lts/

Please also note that, for your security, you should compile downloaded stuff as a non-root user.

Good luck :-)

Please close this issue when OK. Thanks.

**Comment by frederiklikaj** [comment]
Thank you
