### ISSUE TITLE
Can't find usable main.tcl

### ISSUE THREAD

**Issue by smitgd** [monnerat/insight#14]
Any idea what causes this error on insight startup? I see the error when I use the fedora 25 provided insight package (actually only a f24 package is provided). I also see this when I build insight with this git project on an f25 machine. However, the strange thing is another f25 machine it works fine on (or at least it starts up and I see the gui). When I was on f23 over a year ago I had no problem with code built from this project.
```
Can't find a usable main.tcl in the following directories:
    /home/gene/install/insight/share/insight1.0 /usr/share/insight1.0 /usr/share/tcl8.6/insight1.0 /usr/lib64/tcl8.6/insight1.0 /usr/lib64/tk8.6/insight1.0 /usr/share/tk8.6/insight1.0 /home/gene/install/insight/share/redhat/gui/insight1.0 /home/gene/install/insight/lib/insight1.0 /home/gene/install/lib/insight1.0 /home/gene/install/insight/library

/home/gene/install/insight/share/insight1.0/main.tcl: wrong # args: should be "debug subcommand ?arg ...?"
wrong # args: should be "debug subcommand ?arg ...?"
    while executing
"debug"
    (procedure "pref_set_defaults" line 3)
    invoked from within
"pref_set_defaults"
    (file "/home/gene/install/insight/share/insight1.0/main.tcl" line 154)
    invoked from within
"source /home/gene/install/insight/share/insight1.0/main.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $file]"


This probably means that insight wasn't installed properly.

    while executing
"error $msg"
    (procedure "tcl_findLibrary" line 1)
    invoked from within
"tcl_findLibrary insight 1.0 {} main.tcl GDBTK_LIBRARY GDBTK_LIBRARY"
    (procedure "gdbtk_find_main" line 11)
    invoked from within
"gdbtk_find_main"
```

**Comment by monnerat** [comment]
**Please note this repository is no longer maintained nor supported anymore. See README file.**

The stock F25 package works perfectly well, as you have noted on your other machine. For Fedora package problems, please use https://bugzilla.redhat.com/.

For upstream problems, use the sourceware.org mailing list: https://www.sourceware.org/insight/mailinglist.php.

As a hint, there's probably some tcl/tk module around that takes precedence on insight's own debug function (I don't know what, where and why).
Probably there's some tcl/tk file file around polluting the name space, or your installation is corrupted. The fact that you have the same problem with the stock package and with a homemade compiled version on one machine and the other is OK comforts me in this idea.
May be also check the tcl/tk/itcl/itk/iwidgets package are those of the stock distro and up to date. Verify also their integrity.

**Comment by smitgd** [comment]
Thanks for the hints! I remove all the tcl/tk/itcl/itk/iwidgets and associated -devel packages (and a couple dependent but never really used apps) and removed insight pkg and then re-installed insight and now it runs to the gui. Will try the built version next (obtained from the sourceware git).  If I have more issues I will post to insight mail list. Again, thanks for the help.

**Comment by multiplemonomials** [comment]
I ran into the same issue building for MinGW, and fixed it by:

1. open Notepad++, and do a "whole word" find and replace of "debug" with "redhat_debug" in the `share` folder of where insight is installed, with the file extension filter set to "*.tcl"
2.  rename `share/redhat/gui/debug.tcl` to `redhat_debug.tcl`

Unfortunately, once the Insight UI comes up, it totally freezes.  It never responds, and GDB suggests that the freeze is occuring in TCL code.  @monnerat do you know what could be going on with it, or how I can debug this issue?  I'm using Insight from the Git repository in the readme, TCL 8.5 MinGW64, and MSYS 2.
