### ISSUE TITLE
Latest update on upstream broke something

### ISSUE THREAD

**Issue by antony-jr** [monnerat/insight#15]
Hey @monnerat ,

I know that the original repo is at ``` git://sourceware.org/git/insight.git ```  , I **hope** you are the one who made the changes ? ( *Patrick Monnerat* ).  The problem is that the latest update broke insight memory window , When I load a program , nothing is shown but on the previous versions it works great! Any idea why this occured. 

**If you wish to test this bug , Please use my portable version of insight , You don't need to install anything , Just download and mark it executable**.

**COMMIT 3a66ae3:** ( *The version which works good* )
[Download Insight-continuous-x86_64.AppImage](https://github.com/antony-jr/insight/releases/download/continuous/Insight-continuous-x86_64.AppImage)

**COMMIT c06903:** ( *The version which screws the memory window* )
[Download Insight-continuous-x86_64.AppImage](https://github.com/antony-jr/insight/releases/download/4/Insight-continuous-x86_64.AppImage)

**HOW TO EXECUTE APPIMAGE:**

```
 $ # This is how you execute
 $ chmod +x Insight-continuous-x86_64.AppImage
 $ ./Insight-continuous-x86_64.AppImage
```

**Project page for more info:** https://github.com/antony-jr/insight

Thanks for the **patches** and other fixes.  Please keep on doing your stuff.

**Comment by monnerat** [comment]
Thanks for the alert.
It should be fixed now: see https://sourceware.org/git/?p=insight.git;a=commit;h=a3743c8296b1f6251ade5266a62fd4f62e7c45cb

**Comment by antony-jr** [comment]
Thanks for the quick response , I will ping you when the build is done.

**Comment by antony-jr** [comment]
Thank You , The issue is fixed.
Try out the latest build , [Download Insight-continuous-x86_64.AppImage](https://github.com/antony-jr/insight/releases/download/continuous/Insight-continuous-x86_64.AppImage).
