### ISSUE TITLE
infrun.c:5238: internal-error: switch_back_to_stepped_thread: Assertion `!schedlock_applies (1)' failed

### ISSUE THREAD

**Issue by Marek77** [monnerat/insight#2]
I was debugging a multithreaded application when this happened (hit a breakpoint, stepping over in insight's gdb console with "n"). I can reproduce this reliably (have done 3 times in a row); it doesn't happen in commandline gdb.

Fedora 21 x86_64 with insight-7.8.50-4.20140827git.fc21.x86_64, gdb-7.8.2-38.fc21.x86_64, binutils-2.24-30.fc21.x86_64

This looks very similar to https://sourceware.org/bugzilla/show_bug.cgi?id=17408 fixed in gdb 7.8.1 branch from October 29, 2014 (which RedHat has rebased from, according to the gdb rpm changelog). I installed the src.rpm to check, and the fix in gdb/infrun.c is indeed there, as described in https://sourceware.org/ml/gdb-patches/2014-10/msg00634.html

**Comment by monnerat** [comment]
This is not an issue about the current github source.
For Fedora official packages issues, use https://bugzilla.redhat.com/
