### ISSUE TITLE
Would the development of Insight be continued in the future?

### ISSUE THREAD

**Issue by mirage1993** [monnerat/insight#3]
Hi,
I have used Insight for a long time. I also want to know whether this project is still alive or not. After reading a few messages from the mailing list, I find that you have created a git repository. It seems that the project has been restarted.  What can I do for the project? Would the development of Insight be continued in the future?
Thanks.

**Comment by monnerat** [comment]
"restarted" is a big word... I try to keep it alive and maintain it to be compatible with the current version of gdb, while waiting for its official lead developer to migrate it back to the (yet unpopulated) sourceware git repo.
When I have some spare time, I also manage to fix/improve functionalities, like I did recently for the tracepoint interface. There's still a lot of work to do for the tracepoint handling... contributions are welcome.
The mailing list is still the official point of contact: this github repo is only intended to make this software alive and public in absence of upstream reaction. In other words, I'm not the lead developer, so you have to ask your question and show your interest on the list.
Thanks for your comment.
