### ISSUE TITLE
some errors and solutions

### ISSUE THREAD

**Issue by Frogmarch** [monnerat/insight#5]
Hi, 
I want to use insight, but the gdb version is too old at the last release version.
I was excited to find the project. Thank you for developing this tool.

1. when I run insight, it gives error: can't find package tcl8.5
My computer have three version tcl and tk: tcltk, tcl8.4,tcl8.5...
I removed tcltk tcl8.4 tktcl tk8.4 tk8.6, and recompiled. it fixed.

2. when I run insight, it gives error: can't find package itcl3
`sudo apt-get install itcl3`

3. error:can't find package itk3
`sudo apt-get install itk3`

4. error:can't find package iwidgets4
`sudo apt-get install iwidgets4`

**Comment by monnerat** [comment]
The versions listed with "can't find" error messages are only minimum version requirements.
It is likely you have a search path problem.
Please see https://github.com/monnerat/insight/issues/4
