### ISSUE TITLE
unable to install, failed at make

### ISSUE THREAD

**Issue by youeverknow** [monnerat/insight#6]
hi, i followed your instructions (from http://www.dalfonso.co/blog/2016/04/23/setting-insight-debugger-on-ubuntu-16-04-lts/) to install insight debugger in ubuntu 16.04lts, unfortunately it failed at step 10 (make), below is the error message (by the way thanks a lot for bringing back insight):

./gdbtk/generic/gdbtk.c:552:1: error: invalid conversion from ‘void (*)(Tcl_Time*)’ to ‘void (*)(const Tcl_Time*)’ [-fpermissive]
 };
 ^
./gdbtk/generic/gdbtk.c:552:1: error: invalid conversion from ‘int (*)(Tcl_Time*)’ to ‘int (*)(const Tcl_Time*)’ [-fpermissive]
Makefile:2096: recipe for target 'gdbtk.o' failed
make[3]: *** [gdbtk.o] Error 1
make[3]: Leaving directory '/root/insight/bundle/gdb'
Makefile:9006: recipe for target 'all-gdb' failed
make[2]: *** [all-gdb] Error 2
make[2]: Leaving directory '/root/insight/bundle'
Makefile:847: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/insight/bundle'
Makefile:4: recipe for target 'notarget' failed
make: *** [notarget] Error 2

I was able to install insight back in may 2016, but after I reinstall ubuntu and use the latest version error occurred, do you have older version of this?

**Comment by monnerat** [comment]
Many thanks for your problem report.

The failure occurs for Tcl >= 8.6, which declares some procedure arguments as const while they were'nt in 8.5.

I've just pushed a commit that should resolve the problem for 8.6, while retaining 8.5 compatibility: 5e216626c40e77baa780822358b30ca640e94bca.

Please test and keep me informed. Thanks.

**Comment by youeverknow** [comment]
Thanks, problem solved!
