### ISSUE TITLE
*-devel packages needed?

### ISSUE THREAD

**Issue by smitgd** [monnerat/insight#7]
The README does not mention that possibly various -devel packages are also need. With only the listed packages installed I saw a build error. This is on Fedora 23. I installed these extra packages and now it builds OK:
tk-devel
itk-devel
tcl-devel
itcl-devel
Not sure if all are needed. 
Anyhow, thanks for providing this repo!

**Comment by monnerat** [comment]
The -devel packages are specific to distributions, therefore not mentioned in the product README.
For Fedora 23, you can refer to the official rpm spec file for dependencies: http://pkgs.fedoraproject.org/cgit/rpms/insight.git/tree/insight.spec?h=f23
:-)
