### ISSUE TITLE
build of insight can not find Tcl private header files

### ISSUE THREAD

**Issue by rabbitear** [monnerat/insight#8]
Compiling insight fails on Slackware 14.2, which has its default tcl/tk of version 8.6.5.  The message is "Can not find the Tcl private headers", but they do actually exist in /usr/include.  

Here's the end of the output from make:

--snip--
Configuring in ./libgui
configure: loading cache ./config.cache
checking for a BSD-compatible install... /usr/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for x86_64-pc-linux-gnu-gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for x86_64-pc-linux-gnu-ranlib... ranlib
checking for x86_64-pc-linux-gnu-ar... ar
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking for unistd.h... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking sys/file.h usability... yes
checking sys/file.h presence... yes
checking for sys/file.h... yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for raise... yes
checking for random... yes
checking for cygwin32... no
checking for Tcl configuration... found /usr/lib64/tclConfig.sh
checking for existence of /usr/lib64/tclConfig.sh... loading
checking for Tk configuration... found /usr/lib64/tkConfig.sh
checking for existence of /usr/lib64/tkConfig.sh... loading
checking for Tcl private headers... configure: error: could not find private Tcl headers
Makefile:6960: recipe for target 'configure-libgui' failed
make[2]: *** [configure-libgui] Error 1
make[2]: Leaving directory '/home/kreator/dev/GIT/insight/bundle'
Makefile:850: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/kreator/dev/GIT/insight/bundle'
Makefile:4: recipe for target 'notarget' failed
make: *** [notarget] Error 2
--snip--

I've confirmed that the ''private headers" are in /usr/include in slackware, but still I don't know enough about the GNU autotools to find out where it is trying to look for them.

Ideas?

**Comment by rabbitear** [comment]
Figured it out :)

in the file `<sourcedir>/libgui/acinclude.m4` it will look for the private headers in `<includedir>/tcl-private/generic` and `<includedir>/tk-private/generic` .. so made the directory tcl-private and tk-private then made symlinks in those to ../ with the name generic.  Compiled straight away.

Thanks for the great program here!  I'm excited to start using it.

**Comment by monnerat** [comment]
I'm glad you found a workaround!
As you have noted, it's a path detection problem: the real private resources paths are not very well defined by the (i)tcl/tk projects and may vary depending on the distribution.
I do not have a Slackware installation here, but if you can tell me very precisely where the tclInt.h and tkInt.h files are localed relative to TCL_INCLUDE_SPEC or TCL_SRC_DIR, respectively TK_INCLUDE_SPEC or TK_SRC_DIR, I can try to include these paths in the detection. Of course, this will require you help me in testing :-)

**Comment by rabbitear** [comment]
Thanks for the fast reply here.

A couple of things:

1. I actually ran into version conficts as well, mostly with
'iwidgets-4.0.1' which I compiled from source wanting to only deal with
the 3.2+ versions of itcl/itk ... [I have some ideas how to fix this
which I can talk about in just a second] ..

2. that work around come out of me basicly hacking at different versions
of itcl/itk all day yesterday, litterially all day, but I learned alot!
Evenually I had to sleep so will hopefully get to come back to this some
time in the future.

3. I believe its possible to get everything correct, with paths of
includes and also itcl/ickConfig.sh's but it will take a different
approuch than just hacking at it (trial and error wise).  
    - in slackware TCL/TK is somewhat very optional, so I'm thinking it
      may be best to remove those packages (they have 8.6.5 in the
      default install) then recompile some new combination that can
      satisfy the [what I believe any way] need for itcl 3.x versions.

I'd be glad to help, although I'm not always sure when I have extra time
to tackle all the time..

By recompiling everything, I think it would be possible to get the
paths, etc right from the beginning .. I also did get it to compile and
run on a debian based distro in VM, so I can see how it can be done
there.



On Mon, Aug 29, 2016 at 05:11:19AM -0700, monnerat wrote:
> I'm glad you found a workaround!
> As you have noted, it's a path detection problem: the real private resources paths are not very well defined by the (i)tcl/tk projects and may vary depending on the distribution.
> I do not have a Slackware installation here, but if you can tell me very precisely where the tclInt.h and tkInt.h files are localed relative to TCL_INCLUDE_SPEC or TCL_SRC_DIR, respectively TK_INCLUDE_SPEC or TK_SRC_DIR, I can try to include these paths in the detection. Of course, this will require you help me in testing :-)
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/monnerat/insight/issues/8#issuecomment-243106586

-- 
(\ /)
( . .)   Jon's website is here:
c(")(")   http://www.securityrabbit.com

**Comment by monnerat** [comment]
The paths test now seems to satisfy most of the distributions, including cygwin and mingw on W$.
Thus I won't introduce new tests for home-made installations.
If we can stick to standard Slackware stock packages, that's OK.
Else you'll probably have to create a "howto" for your special case...

**Comment by monnerat** [comment]
Closing after lack of activity.
