### ISSUE TITLE
Problems with target=arm-rtems4.12

### ISSUE THREAD

**Issue by smitgd** [monnerat/insight#9]
The primary thing I am seeing is that very often when I debug an RTEMS (embedded RTOS using st-util gdbserver) program I don't see all the expected dashes on the left where breakpoints can be set. This is mainly in the bottom half of the single application file I am debugging. But the dashes at the top are sometimes on comments or blank lines. Then maybe if I make a change in the file (such as changing a comment) and rebuild and reload I then see all the dash marks and can set the breakpoints and the dashes appear on the expected lines. But if I quit the debugger and reload again, with no changes, the original problem recurs.  But sometimes it works, sometimes not; seems kind of random -- not sure why it works sometimes.

The other problem I see is that if I set more than one breakpoint in the application and then, with right click on the red square and attempt to disable or delete a single breakpoint, all breakpoints are disabled or deleted, not just the one right-clicked on. (The breakpoint dialog works OK.) These are h/w breakpoints on rom addresses.

The only modification I made was to configure with --target=arm-rtems4.12  before building the master version.

**Comment by smitgd** [comment]
The RTEMS application file I am trying to set breakpoints in is named init.c.  RTEMS itself links with the newlib library and newlib also contains a file called init.c.  The rtems build does not keep the source for the newlib so it can't be debugged at source level in gdb (except for raw assembly which is OK). However, insight is somehow (randomly?) associating the potential instruction and breakpoints in the newlib's init.c with the RTEMS application's init.c. The application init.c source file shows up OK in insight but the breakpoint markers (dashes on the left) are in wrong places. Even using the "dir" command in the command window to explicitly set the application init.c location first in the gdb search path does not help (the insight source window always showed the correct init.c source lines regardless).
A work-around for this problem is to rename the application init.c to something unique like rtems_init.c.
Note also that I never see this problem when using the command line gdb so it seems that something in insight specific code is the problem.

**Comment by monnerat** [comment]
Hi smitgd,
I understand the problem and I've tried to reproduce it on a "normal" (i.e.: PC with gdbserver) platform, unsuccessfully.
I'm afraid I can't track down the real bug source without being able to reproduce. If you have a recipe to do it without ARM external hardware, I'll be glad to know it.
Happily you can use the renaming workaround.
Regards,
Patrick

**Comment by smitgd** [comment]
Well, I haven't been too concerned about this lately. I found that I can do this gdb command at the console and see both init.c files with the breakpoints dashes in the right place:

dir ./1/2/3/4/5/6/7/

This causes the newlib source files to be seen and debugged in insight. The name clash between the newlib init.c and the application init.c (with no rename) can be resolved when there is a problem at the "file entry box" under the run button by entering 
timer/init.c  for the application or
misc/init.c for the newlib file since their paths are different (even though there is only one init.c in the drop-down list).
The only minor problem is that the dir command only takes effect after insight is restarted, not immediately.
 
This method for debugging external newlib type code in gdb with the help of "dir" is described here:
https://devel.rtems.org/wiki/Debugging/Newlib
So I have no problem if you close this issue.

**Comment by monnerat** [comment]
Fine!
I'm then closing this issue, but feel free to reopen it if you can provide me some recipe not involving foreign material to reproduce it.
